services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ucoparking-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin12345*"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ucoparking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ucoparking-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://ucoparking-sqlserver:1433;databaseName=uco_parking;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "Admin12345*"
      SPRING_DATA_REDIS_HOST: slipless-coach-driftless-74881.db.redis.io
      SPRING_DATA_REDIS_PORT: "19334"
      SPRING_DATA_REDIS_PASSWORD: "lSxGcaw0ha39FDnp9OAUdXsOF9HAPMfg"
      SPRING_DATA_REDIS_SSL_ENABLED: "true"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://dev-kdmu5o5tazgm408k.us.auth0.com/"

    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ucoparking-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  kong:
    image: kong:3.6-ubuntu
    container_name: ucoparking-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong:/kong/declarative
    restart: unless-stopped

  modsecurity:
    image: owasp/modsecurity-crs:nginx
    container_name: ucoparking-waf
    environment:
      BACKEND: "http://ucoparking-kong:8000"
      PORT: "8080"
      MODSEC_RULE_ENGINE: "On"
    ports:
      - "80:8080"
    depends_on:
      - kong
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data: