spring.application.name=notification-gateway
server.port=8084

# Resend API Key - se inyecta como variable de entorno
resend.api.key=${RESEND_API_KEY}
resend.from.email=onboarding@resend.dev

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
