# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE - SQL SERVER
# ===============================
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1434;databaseName=uco_parking;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:Admin12345*}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# AUTH0 / OAUTH2 RESOURCE SERVER
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://dev-kdmu5o5tazgm408k.us.auth0.com/}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE:https://ucoparking-api}

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always