spring.cloud.azure.keyvault.secret.property-sources[0].enabled=false
spring.datasource.url=jdbc:sqlserver://ucoparking-sqlserver:1433;databaseName=uco_parking;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin12345*
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-kdmu5o5tazgm408k.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://ucoparking-api
spring.data.redis.host=slipless-coach-driftless-74881.db.redis.io
spring.data.redis.port=19334
spring.data.redis.password=lSxGcaw0ha39FDnp9OAUdXsOF9HAPMfg
spring.data.redis.ssl.enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=
spring.web.cors.allowed-origins=http://localhost,http://localhost:5173